In [1]:
import numpy as np

In [2]:
import xarray as xr

In [3]:
%matplotlib inline

In [4]:
from matplotlib.pyplot import *

In [5]:
from datetime import datetime

In [6]:
data = np.random.rand(3, 10)

In [7]:
data.shape

(3, 10)

In [22]:
data[data > 0.8] = np.nan
data

array([[        nan,  0.55589243,  0.11753801,  0.08013517,  0.30560374,
                nan,  0.20962094,  0.23187731,  0.06316331,  0.57970108],
       [ 0.38085612,  0.16466536,         nan,  0.77754006,  0.46032132,
         0.69870195,  0.75686837,  0.45285803,  0.22131184,  0.70564802],
       [ 0.48013034,  0.56288659,  0.57884486,  0.76661368,  0.59727641,
                nan,  0.7725577 ,         nan,  0.50381469,         nan]])

In [23]:
a = xr.DataArray(data, dims=['x', 'y'], coords={'x': [10, 20, 30], 'time':datetime(2010, 1, 3)})
a

<xarray.DataArray (x: 3, y: 10)>
array([[        nan,  0.55589243,  0.11753801,  0.08013517,  0.30560374,
                nan,  0.20962094,  0.23187731,  0.06316331,  0.57970108],
       [ 0.38085612,  0.16466536,         nan,  0.77754006,  0.46032132,
         0.69870195,  0.75686837,  0.45285803,  0.22131184,  0.70564802],
       [ 0.48013034,  0.56288659,  0.57884486,  0.76661368,  0.59727641,
                nan,  0.7725577 ,         nan,  0.50381469,         nan]])
Coordinates:
    time     datetime64[ns] 2010-01-03
  * x        (x) int64 10 20 30
  * y        (y) int64 0 1 2 3 4 5 6 7 8 9

In [24]:
datab = data.copy()
datab[datab < .5] = np.nan

In [25]:
datab

array([[        nan,  0.55589243,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,  0.57970108],
       [        nan,         nan,         nan,  0.77754006,         nan,
         0.69870195,  0.75686837,         nan,         nan,  0.70564802],
       [        nan,  0.56288659,  0.57884486,  0.76661368,  0.59727641,
                nan,  0.7725577 ,         nan,  0.50381469,         nan]])

In [26]:
b = xr.DataArray(datab, dims=['x', 'y'], coords={'x': [10, 20, 30], 'time':datetime(2010, 1, 4)})

In [27]:
comb = xr.concat([a, b], 'time')

In [29]:
comb.count(dim='time')

<xarray.DataArray (x: 3, y: 10)>
array([[0, 2, 1, 1, 1, 0, 1, 1, 1, 2],
       [1, 1, 0, 2, 1, 2, 2, 1, 1, 2],
       [1, 2, 2, 2, 2, 0, 2, 0, 2, 0]])
Coordinates:
  * x        (x) int64 10 20 30
  * y        (y) int64 0 1 2 3 4 5 6 7 8 9

In [31]:
comb.max(dim='time')

<xarray.DataArray (x: 3, y: 10)>
array([[        nan,  0.55589243,  0.11753801,  0.08013517,  0.30560374,
                nan,  0.20962094,  0.23187731,  0.06316331,  0.57970108],
       [ 0.38085612,  0.16466536,         nan,  0.77754006,  0.46032132,
         0.69870195,  0.75686837,  0.45285803,  0.22131184,  0.70564802],
       [ 0.48013034,  0.56288659,  0.57884486,  0.76661368,  0.59727641,
                nan,  0.7725577 ,         nan,  0.50381469,         nan]])
Coordinates:
  * x        (x) int64 10 20 30
  * y        (y) int64 0 1 2 3 4 5 6 7 8 9

In [33]:
comb.groupby('time.day').mean(dim='time')

<xarray.DataArray (day: 4, x: 3, y: 10)>
array([[[ 0.6058128 ,  0.41439131,  0.57819417,  0.11189831,  0.07093284,
          0.49545013,  0.00960583,  0.83443594,  0.19037937,  0.15308206],
        [ 0.26699744,  0.59888543,  0.15972862,  0.19820866,  0.45922169,
          0.21900277,  0.5773666 ,  0.73640294,  0.07778405,  0.77081377],
        [ 0.31449483,  0.22698163,  0.94639217,  0.41111678,  0.60665371,
          0.75854892,  0.62022036,  0.67855218,  0.24051055,  0.24616162]],

       [[ 0.6058128 ,  0.41439131,  0.57819417,  0.11189831,  0.07093284,
          0.49545013,  0.00960583,  0.83443594,  0.19037937,  0.15308206],
        [ 0.26699744,  0.59888543,  0.15972862,  0.19820866,  0.45922169,
          0.21900277,  0.5773666 ,  0.73640294,  0.07778405,  0.77081377],
        [ 0.31449483,  0.22698163,  0.94639217,  0.41111678,  0.60665371,
          0.75854892,  0.62022036,  0.67855218,  0.24051055,  0.24616162]],

       [[ 0.6058128 ,  0.41439131,  0.57819417,  0.11189831, 

In [ ]:
ds = comb.to_dataset(name='test')

In [ ]:
ds.to_netcdf('test.nc')

In [ ]:
!mkdir multifile

In [ ]:
!cp test.nc multifile/test2.nc

In [ ]:
ds = xr.open_mfdataset('multifile/*.nc', concat_dim='time')

In [ ]:
ds['time'].values

In [ ]:
ds.sel(time='2010-01-03')

In [ ]:
da = ds['test']

In [ ]:
da.sel(time='2010-01-03').mean(dim='time').plot()